# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=30)),
                ('courseDescription', models.CharField(max_length=30)),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('favorites', models.ManyToManyField(related_name='userFaves', to='loginReg.User')),
                ('userAdded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAdds', to='loginReg.User')),
            ],
        ),
    ]
